include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    format_line_length: 100

analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.chopper.dart"
    - lib/core/l10n/**
code_style:
